apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sliver-sh-http
  namespace: c2
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`sliver.xyz`)
    services:
    - kind: Service
      name: sliver-lh-web
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sliver-sh-https
  namespace: c2
spec:
  entryPoints:
    - https
  routes:
  - kind: Rule
    match: Host(`covenant-lh.xyz`)
    services:
    - kind: Service
      name: sliver-sh-https
      port: 443
#  tls:
#    secretName: ekoparty-tls
