apiVersion: v1
kind: Service
metadata:
  name: cov-lh-web
  namespace: c2
  labels:
    app: covenant-lh
spec:
  ports:
  - port: 80
    name: cov-lh-web
    targetPort: 80
  selector:
    app: covenant-lh
---
apiVersion: v1
kind: Service
metadata:
  name: cov-lh-dashboard
  namespace: c2
  labels:
    app: covenant-lh
spec:
  ports:
  - port: 7443
    name: cov-lh-dashboard
    targetPort: 7443
  selector:
    app: covenant-lh
---
apiVersion: v1
kind: Service
metadata:
  name: cov-lh-https
  namespace: c2
  labels:
    app: covenant-lh
spec:
  ports:
  - port: 443
    name: cov-lh-https
    targetPort: 443
  selector:
    app: covenant-lh
