---
apiVersion: v1
kind: Service
metadata:
  name: kali-sh-web
  namespace: c2
  annotations:
    metallb.universe.tf/address-pool: public
  labels:
    app: kali-sh
spec:
  ports:
    - protocol: TCP
      name: nc-rev-1
      port: 1337
  selector:
    app: kali-sh
  type: LoadBalancer

