apiVersion: v1
kind: Service
metadata:
  name: merlin-lh-web
  namespace: c2
  labels:
    app: merlin-lh
spec:
  ports:
  - port: 80
    name: merlin-lh-web
    targetPort: 80
  selector:
    app: merlin-lh
---
apiVersion: v1
kind: Service
metadata:
  name: merlin-lh-https
  namespace: c2
  labels:
    app: merlin-lh
spec:
  ports:
  - port: 443
    name: merlin-lh-https
    targetPort: 443
  selector:
    app: merlin-lh
