apiVersion: v1
kind: Service
metadata:
  name: cov-sh-web
  namespace: c2
  labels:
    app: covenant-sh
spec:
  ports:
  - port: 80
    name: cov-sh-web
    targetPort: 80
  selector:
    app: covenant-sh
---
apiVersion: v1
kind: Service
metadata:
  name: cov-sh-dashboard
  namespace: c2
  labels:
    app: covenant-sh
spec:
  ports:
  - port: 7443
    name: cov-sh-dashboard
    targetPort: 7443
  selector:
    app: covenant-sh
---
apiVersion: v1
kind: Service
metadata:
  name: cov-sh-https
  namespace: c2
  labels:
    app: covenant-sh
spec:
  ports:
  - port: 443
    name: cov-sh-https
    targetPort: 443
  selector:
    app: covenant-sh
